### ISSUE TITLE
README Typos

### ISSUE THREAD

**Issue by Raboro** [Superschnizel/Obsidian-Moviegrabber#1]
Hi, nice plugin idea. I found a couple of little typos and grammer mistakes in your README.md. I can fix them I a PR or you do:
- Notes -> notes (line 3)
- Movies -> movies (line 3)
- disclaimer -> Disclaimer (line 11)
- plugin -> plugin, (line 13)
- Key -> key (line 13)
- here, -> here (line 13)
- as is -> as (line 13)
- plugins -> plugin (line 13)
- movie -> movie, (line 15)
- Using with -> Using (line 17)
- css -> CSS (line 17)
- snippet -> snippet, (line 19)
- querry -> query (line 32)

**Comment by Superschnizel** [comment]
Thanks, glad you like it. I have fixed the typos you mentioned.
