### ISSUE TITLE
Note not created

### ISSUE THREAD

**Issue by koberulz** [Superschnizel/Obsidian-Moviegrabber#15]
Uncaught TypeError: Cannot read properties of undefined (reading 'view')
    at displayAliases (plugin:frontmatter-alias-display:35:30)
    at e.tryTrigger (app.js:1:695499)
    at e.trigger (app.js:1:695432)
    at t.trigger (app.js:1:2028169)
    at t.updateLayout (app.js:1:2020822)
    at r (app.js:1:1972110)
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)

Uncaught (in promise) TypeError: _a.split is not a function
    at eval (plugin:moviegrabber:2100:59)
    at String.replace (<anonymous>)
    at Moviegrabber.FillTemplate (plugin:moviegrabber:2092:21)
    at Moviegrabber.createNote (plugin:moviegrabber:2063:30)

**Comment by jpfieber** [comment]
I'm getting a similar error with no note generated for a movie:
```
Uncaught (in promise) TypeError: _a.split is not a function
    at eval (plugin:moviegrabber:2100:59)
    at String.replace (<anonymous>)
    at Moviegrabber.FillTemplate (plugin:moviegrabber:2092:21)
    at Moviegrabber.createNote (plugin:moviegrabber:2063:30)
```

**Comment by Superschnizel** [comment]
> Uncaught TypeError: Cannot read properties of undefined (reading 'view') at displayAliases (plugin:frontmatter-alias-display:35:30) at e.tryTrigger (app.js:1:695499) at e.trigger (app.js:1:695432) at t.trigger (app.js:1:2028169) at t.updateLayout (app.js:1:2020822) at r (app.js:1:1972110) at node:internal/process/task_queues:140:7 at AsyncResource.runInAsyncScope (node:async_hooks:204:9) at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
> 
> Uncaught (in promise) TypeError: _a.split is not a function at eval (plugin:moviegrabber:2100:59) at String.replace () at Moviegrabber.FillTemplate (plugin:moviegrabber:2092:21) at Moviegrabber.createNote (plugin:moviegrabber:2063:30)

It seems the first error comes form the [frontmatter-alias-display](https://github.com/muhammadv-i/obsidian-frontmatter-alias-display) plugin. does the error still occur with that plugin disabled?

Are you using a template? if yes, could you share it with me so i can try to reproduce the error?

The same question goes to @jpfieber , as i can not yer reproduce the error.

**Comment by koberulz** [comment]
I removed that plugin, and now I'm jut getting the _a.split error.

**Comment by Superschnizel** [comment]
ah, i see the error, it seems that this error only occurs when using the {{Ratings}} tag. So for now if you use a template without the {{Ratings}} tag it should work fine.

**Comment by koberulz** [comment]
I'm not using {{Ratings}}, I don't think?
[Movie.md](https://github.com/Superschnizel/Obsidian-Moviegrabber/files/13504017/Movie.md)

**Comment by Superschnizel** [comment]
> I'm not using {{Ratings}}, I don't think? [Movie.md](https://github.com/Superschnizel/Obsidian-Moviegrabber/files/13504017/Movie.md)

in the comment section below

**Comment by jpfieber** [comment]
I disabled all of my community plugins and still get the same error. Are their any core plugins that yours relies on? I disable those I don't use.

**Comment by jpfieber** [comment]
I removed {{Ratings}} and it did create a note, but I got an error that "{{totalSeasons}}" could not be created (I imported the movie "Terminator").

**Comment by Superschnizel** [comment]
> I removed {{Ratings}} and it did create a note, but I got an error that "{{totalSeasons}}" could not be created (I imported the movie "Terminator").

Yes, that is by design, you will get notified if a tag could not be resolved (i.e. there is no data for that tag). totalSeasons should get resolved when creating a Note for a series.

**Comment by koberulz** [comment]
> > I'm not using {{Ratings}}, I don't think? [Movie.md](https://github.com/Superschnizel/Obsidian-Moviegrabber/files/13504017/Movie.md)
> 
> in the commented section below the delimiter

Ah, so it's causing problems even though it's commented out? Wild.

Removed that and we're all good.

**Comment by Superschnizel** [comment]
> > > I'm not using {{Ratings}}, I don't think? [Movie.md](https://github.com/Superschnizel/Obsidian-Moviegrabber/files/13504017/Movie.md)
> > 
> > 
> > in the commented section below the delimiter
> 
> Ah, so it's causing problems even though it's commented out? Wild.
> 
> Removed that and we're all good.

Yes, right now the template is applied to everything in the note, i thought about leaving out commented tags but i have not really seen a reason to yet.

I am working on a fix right now and hope to publish the update later.
