### ISSUE TITLE
Error in request while trying to search movie

### ISSUE THREAD

**Issue by d0verenny** [Superschnizel/Obsidian-Moviegrabber#18]
Hi, 

I get this error while trying to search a movie. I got my API key OMDb Api key in place. (v. 1.1.13)

![uj7WFiasWq](https://github.com/Superschnizel/Obsidian-Moviegrabber/assets/28781690/fe91862c-0039-4093-802f-c42bf724f32a)

Also, not sure, but the example template seems to be messed up.

![Obsidian_G6qHJYhzY3](https://github.com/Superschnizel/Obsidian-Moviegrabber/assets/28781690/60d27d98-38b3-4b5d-a900-281d506c70b6)

**Comment by Superschnizel** [comment]
This happens if the plugin can not reach the Omdb API. this can happen because of network problems/ connectivity issues. maybe try if you can access https://www.omdbapi.com/ in your browser and try running the search again.

**Comment by d0verenny** [comment]
> This happens if the plugin can not reach the Omdb API. this can happen because of network problems/ connectivity issues. maybe try if you can access https://www.omdbapi.com/ in your browser and try running the search again.

Yes, I can access it via browser. I even tried searching with VPN on to no avail.

**Comment by d0verenny** [comment]
I found out what the problem was. I should've entered API key only, not the link with the api key. Now it works.

**Comment by Superschnizel** [comment]
> I found out what the problem was. I should've entered API key only, not the link with the api key. Now it works.

Ah i see. Maybe i will add a validation warning, so this does not happen again.
