### ISSUE TITLE
Extract ratings to their own fields

### ISSUE THREAD

**Issue by cstby** [Superschnizel/Obsidian-Moviegrabber#20]
The ratings field from omdb currently returns an array that isn't directly usable in Obsidian.

As discussed in [this issue](https://github.com/omdbapi/OMDb-API/issues/5), omdb doesn't store ratings because of legal issues. Instead, it pulls ratings from other sources.

I believe the most up to date ratings are contained in this array. Making each rating accessible through the template would benefit users of this plugin.

**Comment by Superschnizel** [comment]
I just published 1.1.14, wich introduces Regex Transfomations. These allow you to extract specific reviews, like for example:
```
{{Ratings|"|"|<$Rotten Tomatoes\: .*$>}}
```
Will only show Rotten Tomatoes score.
