### ISSUE TITLE
css is broken

### ISSUE THREAD

**Issue by d0verenny** [Superschnizel/Obsidian-Moviegrabber#22]
![image](https://github.com/Superschnizel/Obsidian-Moviegrabber/assets/28781690/d08a6ea5-5875-44bc-8f0c-6eb525af413b)

I tried to enable css today, and this is what I got.

**Comment by Superschnizel** [comment]
It seems that this comes from the recent changes in Obsidian Tables. This can be fixed by adding `height: auto` to the Title Box (line 127):

```
/* First Column */
/* First Column Box -- TITLE BOX */
.CardViewMovies td:first-child {
    min-height: 75px !important ;
    background-color: rgba(37, 37, 37, 0.863);
    border: 5px solid rgb(48, 48, 48) !important;
    border-radius: 15px;
    display: flex;
    justify-content: center;
    align-items: center;
    height: auto;
}
```

I will push the changes to the repo, but if you need an imediate fix just add this line to the css.

**Comment by d0verenny** [comment]
Thanks! It fixed it.
