### ISSUE TITLE
Search does not find a recent movie despite being present in OMDB

### ISSUE THREAD

**Issue by tumber43** [Superschnizel/Obsidian-Moviegrabber#23]
I searched for a recent 2023 movie called Float, but the correct movie does not show in the list.

I perform the same search on the OMDB site, and with my key/title/year in a url and both find the movie.

Test it yourself, then run it from within Obsidian:

https://www.omdbapi.com/?apikey=[your api key]&t=float&y=2023

Try "float" and "Float 2023"

Its not an issue with the year and there is no alternative name.

**Comment by Superschnizel** [comment]
This is because currently the plugin only uses the title for the search. To work around this you can directly enter an IMDB id (in this case: `tt13205458`) into the search Field. 
Additionaly i might try to add the ability to add a year to the search later.

**Comment by tumber43** [comment]
Thanks for the work around. I still think there is an issue because searching by the name alone does bring up several other films with Float in the name. Maybe its a limit to the list length presented in the popup in obsidian. I notice that there are 10 listed. Maybe this movie would have been the 11th. Also, might be good if the list was sorted with the newer movies at the top. BTW, all complaining and suggestions aside... this is a great addon. I've tried them all and this is the best one for movies and series. Love the custom templates. Thank you.

**Comment by Superschnizel** [comment]
In release 1.1.15 I added the ability to add a year to the search as well as a description text to the search modal to hopefully take care of this issue.
