### ISSUE TITLE
Error: "Missing one or more API keys" when searching for Series

### ISSUE THREAD

**Issue by glenray** [Superschnizel/Obsidian-Moviegrabber#24]
Hello: I am able to search for movies just fine, but when I try to search for a **series**, I get the error: "Missing one or more API keys". This error occurs as soon as I select "Moviegrabber: Search series" from the command menu; there is no prompt for search terms. Selecting "Moviegrabber: Search movies" works as expected.

I have tried:
- exiting and restarting Obsidian;
- turning off the plugin and then back on;
- uninstall plug-in and reinstall;
- I confirmed that this search: (https://www.omdbapi.com/?apikey=[my api key]&type=[series]&t=[The%20Tourist]&plot=full directly to the api gives the correct result (where `my api key` is filled in with my api key;

Otherwise, I am loving the movie search capability.

Many thanks.
Glen

**Comment by Superschnizel** [comment]
Seems like this is because there is no Youtube api key. 
There is a bug, where the command for searching Series was not updated correctly to ignore a missing Youtube API key.
I will publish a fix soon.

**Comment by Superschnizel** [comment]
this is fixed in version 1.1.16
