### ISSUE TITLE
Syntax Error when title or plot contains quotation marks

### ISSUE THREAD

**Issue by MichaelP17** [Superschnizel/Obsidian-Moviegrabber#27]
Whenever a title or a plot contains quotation marks the properties will not load because of a syntax error.
Quotation marks probably need to be escaped or worst case removed.

**Comment by Superschnizel** [comment]
You can get around the issue by using single quotes (`''`) around the properties.

Since i would like to avoid changing the contents of the Data too much i think this workaround is the best way to handle things.

**Comment by Superschnizel** [comment]
Closing this, if there is interest in another solution than the one mentioned above please reopen or create a new issue.
