### ISSUE TITLE
Request: Youtube Folder

### ISSUE THREAD

**Issue by creativefibro** [Superschnizel/Obsidian-Moviegrabber#3]
I have different folders for Movies, TV Series and YouTube Videos but the settings only provide one folder for all of them, would it be possible for the ability to select folders for the three different types of media. Thanks

**Comment by Superschnizel** [comment]
yes that should be possible, i will have a look what i can do.

**Comment by Superschnizel** [comment]
I have just released an update, you can now search for series and chose a folder in wich to save them.
I dont really understand what you need in regards to youtube videos, as this plugin is only used for grabbing movie/series data and (right now) only uses youtube for the trailer embeds. #

**Comment by creativefibro** [comment]
Got it, with it asking for the YouTube API I thought it may be able to bring in the meta details of watched YouTube videos too. No problem.
