### ISSUE TITLE
Add description for frontmatter

### ISSUE THREAD

**Issue by foegra** [Superschnizel/Obsidian-Moviegrabber#30]
Would be good to add in documentation, how to make tags work properly in frontmatter, if tag is a list

**Comment by Superschnizel** [comment]
I added a smal note to the README:


> **Note:**
> The data for some tags come as a list (e.g. `{{Actors}}`). To make these into a valid frontmatter list you can sorround them with square brakets:
> `[{{Actors}}]`

**Comment by foegra** [comment]
solved
