### ISSUE TITLE
Fields inappropriately split on commas

### ISSUE THREAD

**Issue by baodrate** [Superschnizel/Obsidian-Moviegrabber#33]
Some fields (e.g. `BoxOffice`, `imdb_votes`) seem to be treated as lists when they contain commas. For example, the template

```
imdbVotes: {{imdbVotes|<|>}}
BoxOffice: {{BoxOffice|<|>}}
```

with [28 Days Later](https://www.imdb.com/title/tt0289043/) results in:

```
imdbVotes: <454>, <693>
BoxOffice: <$45>, <064>, <915>
```

the commas here should be interpreted as part of a single number, rather than as a value separator

**Comment by Superschnizel** [comment]
In version 1.1.20 I added an exlude list for Fields, so that imdbVotes and BoxOffice are no longer split on Comma.
