### ISSUE TITLE
The folder is no longer being found.

### ISSUE THREAD

**Issue by creativefibro** [Superschnizel/Obsidian-Moviegrabber#4]
I have enclosed a screen shot of the path to my movies folder. I have set up this pathway exactly but when I run the query I just get a pop up error code saying the folder doesn't exist. It worked before the update with the same pathway so I don't know why it is going wrong now? 

![CleanShot 2023-10-25 at 9  02 44@2x](https://github.com/Superschnizel/Obsidian-Moviegrabber/assets/39191327/8b5bd388-7583-49aa-b01f-df4f8cde7229)

https://share.cleanshot.com/xtjpDg6D video of the error

**Comment by Superschnizel** [comment]
I switched around how the paths are created in the last update, sorry about that. I will fix this as soon as possible.
For now to avoid this error message you can remove the "/" at the end of the path. So `Atlas/Notes/Sources/Movies` should work.

**Comment by creativefibro** [comment]
I have tried that already before logging the error but unfortunately it didn’t work.

**Comment by Superschnizel** [comment]
Okay, i have found the issue. I will create an update now, it might take a little bit until it is available in obsidian.
