### ISSUE TITLE
Feature - option to use a template for new notes

### ISSUE THREAD

**Issue by olivr70** [Superschnizel/Obsidian-Moviegrabber#6]
It would be very useful to generate the movie notes with a template

For my usecase, I'd rather have the trailer embed in the note itself, which could be easily done with a template

**Comment by Superschnizel** [comment]
yes, i was planning to allow the customization of how the movie data is saved. I will have a look at how to implement this exactly but using a template seems like a good idea.

What would your ideal version of this feature look like?

**Comment by Superschnizel** [comment]
i have just released an update with this feature. Let me know what you think, if you get around to using it.

**Comment by olivr70** [comment]
Just installed the new version. It works great. Thanks a lot for implementing this suggestion.
