### ISSUE TITLE
Allow overwriting of existing note for a movie

### ISSUE THREAD

**Issue by olivr70** [Superschnizel/Obsidian-Moviegrabber#8]
With the new Template feature, it is often needed when working on the template or to regenerate a note when the template is updated.

It could be made available either as : 
- new commands (Regenerate movie/series) which would run the query on the "imdbId" if present, or "title" if there is only one result
- an option of what to do when the movie note already exists : Keep existing / Ask / Overwrite

More nice to have features could be : 
- an option to set a delimiter string for user added content  below which existing text would be preserved
- a way to regenerate all the notes in the MOVIES and SERIES folders

**Comment by Superschnizel** [comment]
> * new commands (Regenerate movie/series) which would run the query on the "imdbId" if present, or "title" if there is only one result
> 
> * an option of what to do when the movie note already exists : Keep existing / Ask / Overwrite

I will look into this as soon as i have time. should be pretty straight forward though.

**Comment by Superschnizel** [comment]
I have just published an update that does some of the things you asked for. When trying to create a note that already exists you will now be asked if you want to overwrite that note.
You can also use the delimiter string `%%==MOVIEGRABBER_KEEP==%%`. everything below this will still be present in the new note.

if i have some time, i will also try to implement a command to regenerate all notes in the folder soon.

**Comment by olivr70** [comment]
Great. 
But there is problem on my machine. I just installed version 1.1.2. When a note already exists, a message "Creating note..." but nothing happens : the existing note is preserved.

**Comment by Superschnizel** [comment]
Oh, it seems i messed something up when publishing the update, if you try again you should be able to install the newest version 1.1.5 soon.

**Comment by Superschnizel** [comment]
Closing this, since the basic feature exists. I might implement bulk regenerating, but it will require some additional steps to be worth it.
