### ISSUE TITLE
Allow searching a movie by its IMDBid

### ISSUE THREAD

**Issue by olivr70** [Superschnizel/Obsidian-Moviegrabber#9]
This would be useful when adding a movie with an original title in a foreign language. OMDB only has the US title.

In that case  I use IMDB to find the movie (the original title is searchable) to get the US title and fetch the ImdbID from the URL

I then jumps to OMDB site with the API form to query by ImdbId, select the title, go back to Obsidian to find the movie by title.

Searching bu IMDBId would allow skipping the OMSB step. because of their very specific structure, the same query form could probably be used.

**Comment by Superschnizel** [comment]
i have added this in version 1.1.6
You can now enter a valid IMDB id into the search modal and it will automatically detect it and search the movie.
